apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: anz-mortgage-bot-$$APP_PHASE
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mortgage-bot
        phase: $$APP_PHASE
    spec:
      containers:
      - name: mortgage-bot
        #use image from dockerhub for local execution
        image: manglu/mortgage-bot:0.8.1
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 8080
        #Environment variables that are available to the container
        #Secret Name is the binding-<Name-of-Bluemix-Service
        #env:
        #  - name: WCS_SERVICES
        #    valueFrom:
        #      secretKeyRef:
        #        name: binding-wcs
        #        key: binding
